### ISSUE TITLE
Info about player during game

### ISSUE THREAD

**Issue by Ryanm95** [panzarino/mlbgame#100]
It is hard for me to follow the documentation that you provided so I have a question about how to get player stats for a particular game like runs, hits, and home runs.

**Comment by trevor-viljoen** [comment]
```python
from __future__ import print_function
import mlbgame

game = mlbgame.day(2015, 11, 1, home='Mets')[0]
stats = mlbgame.player_stats(game.game_id)
for player in stats.home_batting:
    if player.hr:
        print('{}: {}-{}, {} HR'.format(player.name_display_first_last, player.h, player.ab, player.hr))
    else:
        print('{}: {}-{}'.format(player.name_display_first_last, player.h, player.ab))

**Comment by panzarino** [comment]
@Ryanm95 by using the links on the left side of the documentation page, you can visit the documentation for each module. Within that, there is a list of properties for each object that can be created. So, for stats, the applicable page would be http://panz.io/mlbgame/stats.m.html, which shows the different stat objects and attributes. In this case, you are looking for PlayerStats.
