### ISSUE TITLE
Simple way to Access Live Game Info with a Game ID

### ISSUE THREAD

**Issue by KYDronePilot** [panzarino/mlbgame#101]
I'm working on a project that needs the following information: current inning (including whether top or bottom), current score, and the home and away team names. Is there any simple way to get this information with only a game ID?

**Comment by trevor-viljoen** [comment]
Take a look at the https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard project. They use this API to do that.

**Comment by panzarino** [comment]
@KYDronePilot By looking at the data that is currently available it should be fairly clear about which inning the game is in (along with current score and teams). The `box_score` function accepts a game id and should be pulling the most recent data available. Therefore, the last inning available through that will be the current inning.

**Comment by KYDronePilot** [comment]
Thank you both for your feedback. I overlooked that the `overview` function could also provide all the information I was looking for. Is there any decreased latency advantage (or any advantage, for that matter) to using `box_score` instead of `overview`?

**Comment by panzarino** [comment]
@KYDronePilot I think that they both should be updated in realtime.
