### ISSUE TITLE
Bug - No Output - mlbgame.games

### ISSUE THREAD

**Issue by goodkdh** [panzarino/mlbgame#108]
Hi, 

I've found out that there are NOT Output results for following teams and terms.

1) Team: Diamondbacks, Term: year 2008 ~ 2017
2) Team: Rays, Term: year 2005 ~ 2007

Please fix the issue.
Thanks.
Kim

----------------------------------------------------------------------------
month = mlbgame.games(2007, home='Rays', away='Rays')
games = mlbgame.combine_games(month)
for game in games:
    print(game)
---------------------------------------------------------------------------

-- Normal
![image](https://user-images.githubusercontent.com/42227364/45068360-0c58d780-b102-11e8-85ea-820c7fffff22.png)

--No Output
![image](https://user-images.githubusercontent.com/42227364/45068388-298da600-b102-11e8-81a5-e638cbfd9b4f.png)

**Comment by ajbowler** [comment]
If there's no data coming back that's not on mlbgame, that's on MLB. 2017 for Arizona is certainly a weird outlier but the further back you go you'll find less and less data will be returned from this API due to lack of storage on MLB's part.

**Comment by trevor-viljoen** [comment]
The Rays were called the Devil Rays before 2008.

```python
In [2]: mlbgame.games(2007, home='Devil Rays', away='Devil Rays')
Out[2]:
[[<mlbgame.game.GameScoreboard at 0x10bc04c50>],
 [<mlbgame.game.GameScoreboard at 0x10bc04b00>],
 [<mlbgame.game.GameScoreboard at 0x10bc8ab70>],
 [<mlbgame.game.GameScoreboard at 0x10bc8aa90>],
 [<mlbgame.game.GameScoreboard at 0x10bc8ae48>],
 [<mlbgame.game.GameScoreboard at 0x10bc8af60>],
 [<mlbgame.game.GameScoreboard at 0x10bc8ad30>],
 [<mlbgame.game.GameScoreboard at 0x10bc8ad68>],
...
```

MLB uses `D-backs` for the common name, which I believe is the same as the field the `scoreboard` function finds in looking through scoreboard data files `home_name = teams[0].attrib['name']`. For example: http://gd2.mlb.com/components/game/mlb/year_2008/month_08/day_01/scoreboard.xml, the name here is 'D-backs'. 
```python
In [7]: mlbgame.info.team_info()
Out[7]:
[{'address': '401 East Jefferson Street',
  'aws_club_slug': 'dbacks',
  'city': 'Phoenix',
  'club': 'ari',
  'club_common_name': 'D-backs',
```

```python
In [5]: mlbgame.games(2008, home='D-backs', away='D-backs')
Out[5]:
[[<mlbgame.game.GameScoreboard at 0x10bd19630>],
 [<mlbgame.game.GameScoreboard at 0x10bd192e8>,
  <mlbgame.game.GameScoreboard at 0x10bd19be0>],
 [<mlbgame.game.GameScoreboard at 0x10bd196a0>],
 [<mlbgame.game.GameScoreboard at 0x10bd19e10>],
 [<mlbgame.game.GameScoreboard at 0x10bd11be0>],
 [<mlbgame.game.GameScoreboard at 0x10bd19d68>],
 [<mlbgame.game.GameScoreboard at 0x10bd195f8>,
  <mlbgame.game.GameScoreboard at 0x10bd19978>],
...
```
