### ISSUE TITLE
Requests only return fresh data each minute

### ISSUE THREAD

**Issue by broder22** [panzarino/mlbgame#114]
Any requests within one minute of the original return cached data. Is it possible to disable this behavior for quicker updates from live games? This seems specific to mlbgame.overview()

![mlbgame](https://user-images.githubusercontent.com/20190752/46741587-f8f1dc80-cc6a-11e8-8730-83961768e6c2.png)

**Comment by panzarino** [comment]
@broder22 This seems to be an issue with mlb updating the data on the server. I think they must only update the file every minute, which is causing the delay. The overview function should be getting the most up to date information all the time.
