### ISSUE TITLE
Home/Away Probable Pitchers Reversed

### ISSUE THREAD

**Issue by mjsimpson24** [panzarino/mlbgame#122]
I'm grabbing the probable pitchers for 3/28/2019 and I noticed on the Reds/Pirates game it has Jamison Taillon as the home pitcher & Luis Castillo as the away pitcher when the game is being played in Cincinnati.

**Comment by mrgator85** [comment]
Confirmed.  Checked the Pirates at Reds on 3/28/19 and Astros at Rays on 3/29/19.

**Comment by panzarino** [comment]
That is an issue with the data that mlb.com provides, and is not an issue with this library. This library simply gets the data from mlb.com, so this is not an issue that can be fixed.

**Comment by trevor-viljoen** [comment]
MLB's data source is actually showing things correctly: http://gd2.mlb.com/components/game/mlb/year_2019/month_03/day_28/gid_2019_03_28_pitmlb_cinmlb_1/linescore.xml

**Comment by trevor-viljoen** [comment]
```

**Comment by panzarino** [comment]
Is this the only game that this is happening for or is it also an issue for other games?

**Comment by mrgator85** [comment]
I found two games with the problem. See my comment above. Pit @ Cin and Hou @ Rays

**Comment by trevor-viljoen** [comment]
This looks to be fixed with the master branch.

```    "away_probable_pitcher_name_display_roster": "Taillon",

**Comment by panzarino** [comment]
If it is fixed on master it will be included in the next release (I've been pretty booked the past couple weeks but I'll try to get a release out asap).
