### ISSUE TITLE
How to retrieve first pitch of a game using game_id?

### ISSUE THREAD

**Issue by susarlanikhilesh** [panzarino/mlbgame#125]
I'm trying to retrieve first pitch value for every particular game. I don't find a way. Can you help me through?

Thank you.

**Comment by reddigari** [comment]
I don't think there's a way to query for this, but you can retrieve each game's events in the typical fashion and then access the first pitch:

```Python
events = mlbgame.game_events(game_id)
first_ab = events[0].top[0]
first_pitch = first_ab.pitches[0]  # Pitch object
```

**Comment by susarlanikhilesh** [comment]
I've used https://github.com/trevor-viljoen/mlbgame3 which internally uses panzarino/mlbgame. 
He has directly exposed the api. Almost the same.
Thank you.
