### ISSUE TITLE
Building an updating scoreboard for a day's games

### ISSUE THREAD

**Issue by erinbristow** [panzarino/mlbgame#129]
![Capture](https://user-images.githubusercontent.com/35668184/57799211-67b47e00-7703-11e9-9185-a6a30f751a88.PNG)

Hi, trying to display the day's games and scores and update them every two minutes or so. Not quite sure what going on here, but I'm exploring the different functions listed in the API and I'm having trouble with this one. The result of the function are in hexadecimal. This is also happening for the games() function. Am I missing something? Thanks!

**Comment by AndrewYinLi** [comment]
A list of objects is being returned when you call `scoreboard(...)` and the hexadecimal is the address in memory for the `GameScoreboard` object. I recommend calling `scoreboard(...)[0].__dict__` to see the attributes for the first `GameScoreboard` object.

**Comment by erinbristow** [comment]
Thank you!
