### ISSUE TITLE
long return time waits?

### ISSUE THREAD

**Issue by MatthewDudley** [panzarino/mlbgame#135]
Is anyone else having to wait a long time for calls to return? I got the issue on the example code as well as just printing out one game score.

**Comment by panzarino** [comment]
MLB is moving all of their data away from XML files (what this library uses) and into their own JSON api, and I have noticed that requests for the past ~2 years have been significantly slower than before. Therefore, it seems that MLB is trying to drive everything to their api, rendering this library fairly obsolete.

**Comment by MatthewDudley** [comment]
Thanks for the feedback!
