### ISSUE TITLE
Question: How do I pull a players stats for the entire year?

### ISSUE THREAD

**Issue by jimluke827** [panzarino/mlbgame#25]
Wasn't sure how to mark this as a question, it's not an issue.

How would I code in getting a players stats for the 2015 season for example?

**Comment by zachpanz88** [comment]
@jimluke827
I think you would have to get the data for all of the player's team's games throughout the year with `games`. You would then loop through the games and use the `game_id` to get the player's stats for the game. Then, you can `combine_stats` for each game and search through that list for the individual player's stats. That would be the basic way to get the individual stats for each game, which you could then combine into a final list.

If you're just looking for their season stats, you can find the last game that the player played in and use stat values that are prefixed with `s_`. Any stat that is prefixed with `s_` means that it is the season total up until that game (or pre/postseason total if the game comes from one of those games).

Hopefully this helps, let me know if you need more help or clarification.

**Comment by jimluke827** [comment]
@zachpanz88 
thank you for that response, very helpful. I'll let you know if it gets me anywhere.

What I basically want to do is populate a list of the players season stats (that are available 2012-present). And start created charts/graphs with a stat like BABIP so I can see how is kind of "due" for large positive & negative regressions.

**Comment by jimluke827** [comment]
@zachpanz88 
You "s_" suggestion is working great. I would like to be able to get "s_ab". I am not the best python user (I just started learning). Is there a way I can get that to populate by adding it to the statmap (and probably elsewhere to collect the data)?

**Comment by zachpanz88** [comment]
@jimluke827 the statmap file only provides a directory of stats and what they mean, so a stat may appear that isn't documented in there (such as `s_ab`). If there is no `s_ab` property of the object that is returned, it means that mlb.com does not provide it. However, to get season at bats  you can just divide season hits by batting average (`s_h/avg`), which I believe are both provided.

**Comment by panzarino** [comment]
@jimluke827, did my suggestion work for you? If so, can this issue be closed?

**Comment by jimluke827** [comment]
Yes, this can be closed, thank you.
