### ISSUE TITLE
Groundouts-flyouts in pitcher results?

### ISSUE THREAD

**Issue by FlowFX** [panzarino/mlbgame#30]
On mlb.com, they show the number of flyouts and groundouts for each pitcher.

![screen shot 2017-05-07 at 09 43 01](https://cloud.githubusercontent.com/assets/800345/25782130/d3999ed8-3309-11e7-9bdf-4f60e39b6ee6.png)

I can't find these in the player_stats. Does the API provide this information at all?

**Comment by panzarino** [comment]
@FlowFX I am not sure, I will check it out.

**Comment by digitalSaint** [comment]
@panzarino `rawboxscore.xml` contains that info.

**Comment by ajbowler** [comment]
@panzarino @trevor-viljoen I'd like to take a crack at this if you're cool with adding the feature.

I looked through the XMLs and indeed rawboxscore.xml is the only place I can find groundouts/flyouts (GO/AO). Do you have any concerns about adding the extra network call/XML tree parse?

**Comment by panzarino** [comment]
@ajbowler Go for it! Would love to have a new feature for the library. For larger features, please try to keep the format similar to the way that the current functions work (although the design is not the best, I want to keep it consistent at this point).

**Comment by ajbowler** [comment]
I'll add the two stats to the existing `player_stats` call, I'm not seeing any additional stats the extra XML file gives us at the moment but I'll keep an eye out and open new issues if the data contains any further value

**Comment by panzarino** [comment]
@ajbowler If you're changing the `player_stats` call could you also look at #57? If not, I can fix it but I figured it would be an easy fix and you would need that to work in order to properly test anyway.

**Comment by ajbowler** [comment]
It shouldn't impact either way since I'm grabbing stuff off the pitchers instead of the batters, but I can take a look while I'm in there.
