### ISSUE TITLE
Question: League Standings

### ISSUE THREAD

**Issue by chrissmithto** [panzarino/mlbgame#31]
I hope this is the proper place to ask a question. If not please forgive me. I have been playing around with mlbgame and am looking for a way to generate the current standings by league and division. Is this at all possible?
Example: 

American League East
1 Yankees     21-10
2 Orioles      21-11
3 Red Sox    17-16
4 Rays         17-19
5 Blue Jays 13-21
......

**Comment by digitalSaint** [comment]
It is possible to get the information as a json payload, but not currently a part of the mlbgame code base. It could be added as a new feature, I'm sure. If I get some spare time, I'll look making a pull request if @panzarino doesn't get to it first.

**Comment by panzarino** [comment]
@digitalSaint I would definitely accept a PR with this functionality.

**Comment by bradleyhurley** [comment]
Should this issue be closed?

**Comment by panzarino** [comment]
@bradleyhurley I'm going to close the issue once standings are implemented into an official release (which should be coming soon).

**Comment by panzarino** [comment]
Closing even though the release has not happened yet (it is coming soon).
