### ISSUE TITLE
Player ID for probable starting pitcher

### ISSUE THREAD

**Issue by FlowFX** [panzarino/mlbgame#32]
In `game.scoreboard` the names and win/loss records of the probable starting pitchers are added to the game data.

```python
# games that were not played
    elif game_tag == "sg_game":
        try:
            p_pitcher_data = game.findall('p_pitcher')
            p_pitcher_home_data = p_pitcher_data[0]
            p_pitcher_home = p_pitcher_home_data.find('pitcher').attrib['name']
            p_pitcher_home_wins = int(p_pitcher_home_data.attrib['wins'])
            p_pitcher_home_losses = int(p_pitcher_home_data.attrib['losses'])
```

How could I add the player ID for the starting pitchers? I see them in the `linescore.xml`, but just adding

```python
p_pitcher_home_id = p_pitcher_home_data.find('pitcher').attrib['id']
```
doesn't work. Which data file is read here exactly?

**Comment by panzarino** [comment]
It is using `scoreboard.xml` which contains all the games for that day (it is not in a subfolder with the specific game). I'll look into seeing if there is a way to get the probable pitcher id from that file, and if there is not, I will get it from `linescore.xml`.

**Comment by panzarino** [comment]
@FlowFX if you want to continue contributing in the future, I have set up a mlbgame Slack that you can join through this link: https://join.slack.com/mlbgame/shared_invite/MjAzMjY1MjkwOTAwLTE0OTg0MTI2MjAtMzc2NjJlMzhmYw
