### ISSUE TITLE
Diamondbacks and Athletics cause empty result

### ISSUE THREAD

**Issue by kylefrost** [panzarino/mlbgame#45]
Love the API, but found a small problem. When filtering mlbgame.day() by home or away team, using "Diamondbacks" or "Athletics" will result in an empty set. This is due to the MLB's XML having these listed as "D-backs" and "A's", respectively. Just wanted to let you know in case you wanted to add something to account for it, or let people know in the docs. I'm sure this causes issues in other parts of the API as well, but I've only tested with mlbgame.day().

**Comment by panzarino** [comment]
It will also affect `games()` for sure. I'll add something to the documentation in the upcoming release.
