### ISSUE TITLE
Stats Class not Accepting Subscripts

### ISSUE THREAD

**Issue by robotallie** [panzarino/mlbgame#48]
Having a little trouble getting player info from stats class:
I created a combined games list for 2003, then for each game, tried to get player stats but got an error message.

![mlbgame-stats-not-subscriptable](https://user-images.githubusercontent.com/25355300/32851296-97c0c004-ca02-11e7-9349-ef9bd026abd5.jpeg)

The same problem happens when I try to replicate your example from the mlbgame module home page:
![image](https://user-images.githubusercontent.com/25355300/32851605-6829bf16-ca03-11e7-8676-c0e3fa5228a0.png)

**Comment by panzarino** [comment]
@robotallie I think you are looking at an outdates example (which is my fault that I have not updated it). Stats has been converted to an object rather than a dictionary. Therefore you should use ```stats.home_batting` rather than ```stats['home_batting']``` to achieve the same effect.

**Comment by robotallie** [comment]
Fantastic. I notice that when downloading all the games for 2003, the list
has only a few games total. Does the API have only a selected set of games?

**Comment by panzarino** [comment]
@robotallie this API has all the data that mlb.com has so if mlb doesn't provide it then I don't have it. I guess mlb just doesn't have the data for 2003 (or the URL scheme is different, I've been using the scheme from 2015)
