### ISSUE TITLE
Parsing top of inning twice

### ISSUE THREAD

**Issue by Mslaster** [panzarino/mlbgame#49]
It looks like, when parsing through game events, the events recorded in the bottom of the inning are repeated for the top.
![screen shot 2017-12-27 at 12 01 43 pm](https://user-images.githubusercontent.com/19195667/34387714-cacc28fa-eafd-11e7-9e94-3559ac99710f.png)
 I know that mlbam recently updated their api, so it could affect the formatting.

**Comment by panzarino** [comment]
@Mslaster If MLB has recently updated their api, that is probably the issue. I will look into it. I would be happy to accept a pull request with the bug fix if you are interested in contributing.

**Comment by Mslaster** [comment]
It looks like the raw file is still the same...not totally sure what the issue might be.

I know that MLBAM totally redid their api, with many more things over here : [https://statsapi.mlb.com/docs/](url), but looks like the structure is totally different.

**Comment by panzarino** [comment]
I believe that this issue was fixed somewhere along the line so I am closing this issue.
