### ISSUE TITLE
Away batting?

### ISSUE THREAD

**Issue by JonathanSFalk** [panzarino/mlbgame#57]
Hi.  I just came across this fantastic piece of work today.  Thanks so much.  I'm fairly new to Python, but I can't figure out what I'm doing wrong.  This piece of code:
 ```
stats = mlbgame.player_stats(game.game_id)
    for player in stats.home_batting:
     ... stuff here on player
```
works fine
But this code
```
stats = mlbgame.player_stats(game.game_id)
    for player in stats.away_batting:
     ... stuff here on player
```
Never executes because away_batting is always empty.  I presume I'm doing something wrong, but if I'm not....

**Comment by panzarino** [comment]
I think it should work, it may not since I recently changed the way that the algorithm works for that section. Are the away players showing up in the home section or are they just not there at all? Is this an issue isolated to a specific game or happening for all of them?

**Comment by panzarino** [comment]
@JonathanSFalk I'll investigate more today and try to fix it, if I can't then I'll revert to the old version.

**Comment by ajbowler** [comment]
@JonathanSFalk can you pull latest master and give it another go?

**Comment by panzarino** [comment]
@JonathanSFalk @ajbowler Adding on to that, a release with the fix should be coming by this weekend at the latest, theres a few more things I want to fix before releasing.

**Comment by JonathanSFalk** [comment]
Should have time to look at it tonight.  Thx to both of you.

**Comment by JonathanSFalk** [comment]
Works!  Thanks!
