### ISSUE TITLE
Can't duplicate example results

### ISSUE THREAD

**Issue by Bill-M123** [panzarino/mlbgame#60]
Before I start, a quick thanks for making this available.

I installed 2.4.2 today on my Windows 7 machine with a straightforward pip install and thought things were fine, but  I was unable to duplicate the results shown on the web.  I used this code:

game = mlbgame.day(2015, 11, 1, home='Mets')[0]
stats = mlbgame.player_stats(game.game_id)
for player in stats.home_batting:
    print(player)

and got these results (names and positions, but no actual stats).  Did I miss a step somewhere?

Curtis Granderson (RF)
David Wright (3B)
Daniel Murphy (2B)
Yoenis Cespedes (CF)
Juan Lagares (CF)
Lucas Duda (1B)
Travis d'Arnaud (C)
Michael Conforto (LF)
Wilmer Flores (SS)
Matt Harvey (P)
Jeurys Familia (P)
Kelly Johnson (PH)
Jonathon Niese (P)
Addison Reed (P)
Bartolo Colon (P)

Any thoughts?
-Bill

**Comment by panzarino** [comment]
When printing out an object, python automatically calls the `__str__` method (the same way `toString` works in Java). Each player is an object with multiple properties, its just that when the objects are printed it shows just their name.

**Comment by Bill-M123** [comment]
Thanks.  I was able to access the stats I was looking for through your stats module.  I'll use that for now come back to specialized print statements if necessary.  I said this before, but thanks again for making this available.
