### ISSUE TITLE
Season stats not found

### ISSUE THREAD

**Issue by Hisairnessag3** [panzarino/mlbgame#61]
So I have a simple loop looking for stats like so:

```
def test_stats(games):
    for game in games:
        stats = mlbgame.team_stats(game.game_id)
        hr_home = stats.home_batting.hr
        hr_away = stats.away_batting.hr
        box_score = mlbgame.box_score(game.game_id)
        error_home = box_score.print_scoreboard()
        pitch_home = stats.home_pitching.so
        pi_home = stats.home_pitching.s_h
        print hr_away,hr_home,pitch_home,pi_home
```

when I run this, it is giving me: `AttributeError: 'TeamStats' object has no attribute 's_h'`

Is this another break?

**Comment by Hisairnessag3** [comment]
Also I should probably make another issue for this but when iterating through stats for the year I get this traceback:

```
Traceback (most recent call last):
  File "/Users/austinglugla/PycharmProjects/mlb/mlb.py", line 117, in <module>
    test_stats(games)
  File "/Users/austinglugla/PycharmProjects/mlb/mlb.py", line 58, in test_stats
    box_score = mlbgame.box_score(game.game_id)
  File "/Users/austinglugla/anaconda2/lib/python2.7/site-packages/mlbgame/__init__.py", line 190, in box_score
    data = mlbgame.game.box_score(game_id)
  File "/Users/austinglugla/anaconda2/lib/python2.7/site-packages/mlbgame/game.py", line 240, in box_score
    home = x.attrib['home']
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'home'
```

**Comment by panzarino** [comment]
@Hisairnessag3 try updating to the latest version. I'm pretty sure a similar bug fix was just released. If that doesn't work, I'll look into it further.

**Comment by Hisairnessag3** [comment]
Yes, I am up to date.

**Comment by trevor-viljoen** [comment]
The pitching `TeamStats` object doesn't have a `s_h` property. It comes from this line in the xml:
`<pitching team_flag="home" out="27" h="8" r="4" er="2" bb="3" so="11" hr="0" bf="39" era="1.50">`. 

Each individual pitcher has a `s_h` property: 
```
<pitcher id="434378" name="Verlander" name_display_first_last="Justin Verlander" pos="P" out="6" bf="8" er="0" r="0" h="1" so="2" hr="0" bb="1" np="17" s="11" w="0" l="0" sv="0" bs="0" hld="0" s_ip="2.0" s_h="1" s_r="0" s_er="0" s_bb="1" s_so="2" game_score="50" era="0.00"/>
``` 

Here's a sample boxscore: http://gd2.mlb.com/components/game/mlb/year_2017/month_02/day_25/gid_2017_02_25_houmlb_detmlb_1/boxscore.xml

**Comment by panzarino** [comment]
Closing as @trevor-viljoen has provided the correct answer.

**Comment by Hisairnessag3** [comment]
Any way to grab those types of season stats at the game level? Would be really helpful for what I am doing.

**Comment by trevor-viljoen** [comment]
@Hisairnessag3 Something like this would probably work.

```
player_stats = mlbgame.player_stats(game.game_id)
pi_home = sum([p.s_h for p in player_stats.home_pitching])
```
