### ISSUE TITLE
'module' object has no attribute 'day'

### ISSUE THREAD

**Issue by kcossel** [panzarino/mlbgame#63]
I'm trying to run the sample script from the readme and keep getting the same error.

Traceback (most recent call last):
  File "mlbgame.py", line 2, in <module>
    import mlbgame
  File "/home/pi/mlbgame.py", line 4, in <module>
    game = mlbgame.day(2015, 11, 1, home='Mets')[0]
AttributeError: 'module' object has no attribute 'day'

I am using the newest version of mlbgame.  I have tried this on Windows 7, Linux Mint, and a Raspberry Pi.  Python 2.7 and Python 3.   I get the same error on every machine.   Is there somethin I'm dowing wrong?

**Comment by trevor-viljoen** [comment]
How did you install mlbgame? The easiest was is via pip. ```pip install mlbgame```

From your error, it looks like you created a file called `mlbgame.py` and with this code in it. Rename that file to something else and try again. Python is confused by the namespace, meaning your file has the same name as the mlbgame module you are trying to import classes from.

**Comment by kcossel** [comment]
The filename was the problem, sadly this is not the first time I've done this.  It was trying to import itself.  Once I changed it the program ran.  Thanks.
