### ISSUE TITLE
AttributeError: 'Overview' object has no attribute 'home_probable_pitcher_s_era'

### ISSUE THREAD

**Issue by Hisairnessag3** [panzarino/mlbgame#66]
```
for game in games:
        stats = mlbgame.team_stats(game.game_id)
        overview = mlbgame.overview(game.game_id)
        player_stats = mlbgame.player_stats(game.game_id)
        winning_team_SP_era = overview.home_probable_pitcher_s_era
   
```

**Comment by Hisairnessag3** [comment]
is the wrong XML being parsed. I get the correct values here: http://gd2.mlb.com/components/game/mlb/year_2016/month_08/day_05/gid_2016_08_05_miamlb_colmlb_1/gamecenter.xml

**Comment by ajbowler** [comment]
What's the game ID you're using for overview?

Also those changes were just merged into master a couple days ago, if you're using a released version of mlbgame those attributes won't work till next release.

**Comment by trevor-viljoen** [comment]
Overview doesn't have a `home_probable_pitcher_s_era` key. It comes from `linescore.xml`: https://github.com/panzarino/mlbgame/blob/master/mlbgame/data.py#L80-L82

http://gd2.mlb.com/components/game/mlb/year_2016/month_08/day_05/gid_2016_08_05_miamlb_colmlb_1/linescore.xml

**Comment by ajbowler** [comment]
@trevor-viljoen so games in the past won't have those attributes, but future games will (as of 3/2, this game is future http://gd2.mlb.com/components/game/mlb/year_2018/month_03/day_03/gid_2018_03_03_arimlb_lanmlb_1/linescore.xml)

I recently did https://github.com/panzarino/mlbgame/pull/64 which grabbed the home and away probable starter attributes and if they don't exist, they should all be defaulting to an empty string, which prompted my question to the OP on if they're using a released version of mlbgame or master.

**Comment by trevor-viljoen** [comment]
@ajbowler @panzarino Maybe we should create a FAQ for common issues/assumptions?

**Comment by panzarino** [comment]
@trevor-viljoen FAQ could be a good idea. Will add these new stats in the next release.

**Comment by Hisairnessag3** [comment]
Copy that, just so you know where I am looking: 

```
class Overview(mlbgame.object.Object):
    """Object to hold an overview of game information
    Properties:
          ....
        away_probable_pitcher_first
        away_probable_pitcher_first_name
        away_probable_pitcher_id
        away_probable_pitcher_last
        away_probable_pitcher_last_name
        away_probable_pitcher_losses
        away_probable_pitcher_name_display_roster
        away_probable_pitcher_number
        away_probable_pitcher_s_era
        away_probable_pitcher_s_losses
        away_probable_pitcher_s_wins
        away_probable_pitcher_stats_season
        away_probable_pitcher_stats_type
        away_probable_pitcher_throwinghand
        away_probable_pitcher_wins
```

I need some of this data for stuff I am working on, so I might go ahead and make some changes to grab additional stats via those gamecenter, and linescore structures. Will submit a PR with the updates if that happens.

**Comment by Hisairnessag3** [comment]
Quick question for you guys: Do you know any place to grab the hbp for pitchers?

**Comment by trevor-viljoen** [comment]
@Hisairnessag3 Slack is probably a more appropriate place for questions and you'd get more eyes and a quicker response.

This would get you key, value pairs for pitcher player IDs and how many hit by pitch.  I don't see where MLB has supplied this information in any of the available XML files.

```python
import mlbgame
from collections import Counter

# game_id = 'your_game_id'
events = mlbgame.events(game_id)
half_inn = ['top', 'bottom']
hbp_list = []

for inning in events:
    for half in half_inn:
        for ab in inning.__dict__[half]:
            if ab.event == 'Hit By Pitch':
                hbp_list.append(ab.pitcher)

hbp = Counter(hbp_list)
```

Or with a list comprehension
``` python
import mlbgame
from collections import Counter

# game_id = 'your_game_id'
events = mlbgame.events(game_id)
half = ['top', 'bottom']
hpb_list = [ab.pitcher for inn in events for h in half for ab in inn.__dict__[h] if ab.event == 'Hit By Pitch']
hbp = Counter(hbp_list)
```

**Comment by trevor-viljoen** [comment]
```python
import mlbgame
from collections import Counter

game = mlbgame.day(2017, 11, 1, away='Astros')[0]
events = mlbgame.game_events(game.game_id)
hpb = Counter([ab.pitcher for inn in events for h in half for ab in inn.__dict__[h] if ab.event == 'Hit By Pitch'])
```
```
Counter({621121: 4})
```
[2017 WS Game 7](https://www.mlb.com/gameday/astros-vs-dodgers/2017/11/01/526517#game_state=final,game_tab=box,game=526517)

McCullers hit 4:
```
Turner (by McCullers Jr.); Puig (by McCullers Jr.); Hernandez (by McCullers Jr.); Turner (by McCullers Jr.).
```

**Comment by Hisairnessag3** [comment]
Whats the slack? Thanks, I am assuming I cannot grab the season HBP per game based on the xml(unless you can think of something), so I will calculate it per game and then sum after.

**Comment by trevor-viljoen** [comment]
Slack: https://mlbgame-slack-invite.herokuapp.com/

The XML files used by `mlbgame` are the same files generated by the Game Day application during a given game. Season stats would be stored in a database and not generated at run time by the application. So any season stats shown in the app would likely be the result of an API/DB query made by the application. 

I'm working on v3 of `mlbgame` which uses the MLB stats APIs, but they aren't well documented and some of the APIs don't seem to work, including the endpoint to get season stats.

This is all you get for player pitching stats. The stat would be `hb` for hit batsmen, but isn't part of their pitching stats.
```json
{
  "id": 621121,
  "name": "McCullers Jr.",
  "name_display_first_last": "Lance McCullers Jr.",
  "pos": "P",
  "out": 7,
  "bf": 13,
  "er": 0,
  "r": 0,
  "h": 3,
  "so": 3,
  "hr": 0,
  "bb": 0,
  "np": 49,
  "s": 27,
  "w": 1,
  "l": 0,
  "sv": 0,
  "bs": 0,
  "hld": 0,
  "s_ip": 7.2,
  "s_h": 7,
  "s_r": 3,
  "s_er": 3,
  "s_bb": 4,
  "s_so": 6,
  "game_score": 51,
  "era": 3.52
}
```
