### ISSUE TITLE
game status is 'PRE_GAME' even for games in past that are already completed

### ISSUE THREAD

**Issue by reverett4994** [panzarino/mlbgame#67]
To start let me say I am new to Python so the issue is probably something I missed but when getting scores for games before the 2018 year everything works as expected like so
month = mlbgame.games(2015, 6, home='Mets')
games = mlbgame.combine_games(month)
for game in games:
    print(game)

Giants (5) at Mets (0)
Giants (8) at Mets (5)
...

but when I change the date to anything this year like 2018, 3, 1 I get the game(s) but the game_status is pre_game and all the scores and stats are blank or zero.

month = mlbgame.games(2018, 2, home='Mets')
games = mlbgame.combine_games(month)
for game in games:
    print(game)

Braves (0) at Mets (0)
Cardinals (0) at Mets (0)
Marlins (0) at Mets (0)
Astros (0) at Mets (0)

I'm not sure if its something on my end or if MLB just hasn't updated those games but if anybody could help me understand why this is happening I would be grateful. Thanks for the help!

**Comment by ajbowler** [comment]
It's on MLB's end. I've experienced this as well and my guess is because it's spring training games so things are a little weird.

**Comment by panzarino** [comment]
I assume it has to do with the games being preseason. I am not sure why MLB is not providing the correct data.

**Comment by reverett4994** [comment]
Thanks for the replies and insight, and for the awesome API!
