### ISSUE TITLE
Is a way to get 'action's from game_events.xml?

### ISSUE THREAD

**Issue by jfeeneywm** [panzarino/mlbgame#69]
In __inning_info(inning, part) we use half.findall('atbat') this leaves us unable to see the 'actions' - things like substitutions, steals, etc.. That'd be helpful for what I'm trying to do.

I suppose we could just add another loop similar to the 'atbat' loop to __inning_info()? Would that work?

**Comment by panzarino** [comment]
@jfeeneywm That could definitely be added, I'll look into it.
