### ISSUE TITLE
Is this possible: Players season stats up to a specific date in a season?

### ISSUE THREAD

**Issue by nhiggs** [panzarino/mlbgame#76]
Would it be possible to get a/each players stats at a particular point in time in a previous season?

For example, there was a game between the Cardinals and the Cubs on April 5th 2015. Would it be possible to somehow get what would have been the players season stats (2015) prior to that game?

My initial thought was to loop through each player in each teams roster, and then use player_stats() on each game id up to that point and simply sum each games stats. Would this work? Do you guys have a better way to go about this with your API?

**Comment by trevor-viljoen** [comment]
That would be the only way with the game day data. Keep in mind that there is the potential that the data would have some inaccuracies as you would have to tally it up yourself. There is a MLB Stats API, but it doesn't appear to allow for a date range, only seasonal and situational data.

April 5th, 2015 was opening day for the Cardinals, so there wouldn't be any season stats for them.

As an example, let's say that you wanted each player's season stats up to April 30th. You could do something like this:

```python
#!/usr/bin/env python
from __future__ import print_function
import mlbgame

def insert_or_append(player, stats):
    if player.id not in stats.keys():
        stats[player.id] = [player]
    else:
        stats[player.id].append(player)

my_team = 'Cardinals'
opening_day = 5
batting_stats = {}
pitching_stats = {}

games = mlbgame.games(2015, 4, list(range(opening_day,31)), home=my_team, away=my_team)
games = mlbgame.combine_games(games)

for game in games:
    overview = mlbgame.overview(game.game_id)
    if overview.status != 'Postponed':
        player_stats = mlbgame.player_stats(game.game_id)
        if overview.away_team_name == my_team:
            for player in player_stats.away_batting:
                insert_or_append(player, batting_stats)
            for player in player_stats.away_pitching:
                insert_or_append(player, pitching_stats)
        else:
            for player in player_stats.home_batting:
                insert_or_append(player, batting_stats)
            for player in player_stats.home_pitching:
                insert_or_append(player, pitching_stats)


# Example:
# batting_stats =
#  { 
#    12345: [<mlbgame.stats.PlayerStats object>, <mlbgame.stats.PlayerStats object>],
#    23456: [<mlbgame.stats.PlayerStats object>], ...
#  }
#
# 
# def do_some_calculations(stats):
#    """ Some function to loop through stats """
```

**Comment by panzarino** [comment]
@nhiggs Actually, any stats for a certain game that are prefixed with `s_` are the season stats up to that game.

**Comment by trevor-viljoen** [comment]
@panzarino nice! Good to know. @nhiggs disregard my previous post.

**Comment by trevor-viljoen** [comment]
Looks like you can get season BB, ER, H, IP, R, strike outs for pitching and season BB, H, HR, R, RBI, strike outs for batters. If you check that in post-season play, it will be for that series. If you need to calculate anything else, you'll have to use some code like I shared previously to compile the numbers.

**Comment by nhiggs** [comment]
Thanks for the quick responses. This is actually amazing news for me... :)

**Comment by panzarino** [comment]
Closing as it appears that this issue is solved 😄
