### ISSUE TITLE
GameScoreboard.date is off by one hour for evening games

### ISSUE THREAD

**Issue by dowski** [panzarino/mlbgame#77]
Here's an example. The Indians' opener against the Mariners is at 10:10PM EDT tomorrow. However, `GameScoreboard.date` represents it as 9:10PM.

```
>>> s = mlbgame.day(2018, 3, 29, home="Indians", away="Indians")[0]
>>> s.game_start_time
'10:10PM'
>>> s.date
datetime.datetime(2018, 3, 29, 21, 10)
>>> s.date.strftime("%I:%M%p")
'09:10PM'
```

I'll get a pull request ready.

**Comment by trevor-viljoen** [comment]
looks like this line: https://github.com/panzarino/mlbgame/blob/master/mlbgame/game.py#L214

If PM, it adds 11 rather than 12 hours.

**Comment by dowski** [comment]
Yep.

**Comment by dowski** [comment]
Just saw this today.

```
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2018/03/29 12:40 pm' does not match format '%Y/%m/%d %I:%M%p'
```

Looks like there can be a space between the time and the AM/PM designation sometimes. I'll need to account for that.

**Comment by dowski** [comment]
Updated the PR to account for that scenario.

**Comment by panzarino** [comment]
Merged.
