### ISSUE TITLE
All example snippets returning None

### ISSUE THREAD

**Issue by mccartneyb** [panzarino/mlbgame#82]
Question: New to python but this library seems amazing. I tried copying and pasting the sample code in the documentation but they return None. What am I doing wrong??

**Comment by trevor-viljoen** [comment]
How did you install the module and how are you trying to run the sample code?

**Comment by mccartneyb** [comment]
i installed it via pip install mlbgame and then ran pip install mlbgame --upgrade
mlbgame and lxml were both up to date.

I just copied and pasted the snippets from the documentation, and it returns None for each example:
`from __future__ import print_function
import mlbgame

month = mlbgame.games(2015, 6, home='Mets')
games = mlbgame.combine_games(month)
for game in games:
    print(game)`

**Comment by trevor-viljoen** [comment]
Interesting. This is what I get. I pasted the sample code into `ipython`.

```python
In [2]: from __future__ import print_function
   ...: import mlbgame
   ...:
   ...: month = mlbgame.games(2015, 6, home='Mets')
   ...: games = mlbgame.combine_games(month)
   ...: for game in games:
   ...:     print(game)
   ...:
Giants (5) at Mets (0)
Giants (8) at Mets (5)
Giants (4) at Mets (5)
Braves (3) at Mets (5)
Braves (5) at Mets (3)
Braves (8) at Mets (10)
Blue Jays (3) at Mets (4)
Blue Jays (2) at Mets (3)
Reds (1) at Mets (2)
Reds (1) at Mets (2)
Reds (1) at Mets (2)
Reds (2) at Mets (7)
Cubs (1) at Mets (0)
```

What does `print(month)` and `print(games)` output?

**Comment by mccartneyb** [comment]
I’ll try as soon as I get home. Maybe it’s an issue with my python? I’m using PyCharm I do t know if that makes a difference either. Thanks for the speedy replies, I’ll get back to you as soon as I check!

**Comment by mccartneyb** [comment]
I've tried again, and still return the same result: 'None'
I am using PyCharm 2017.3.4 Community Edition
Python 3.6

Here are links to both code and pip cmd line
[PyCharm](https://ibb.co/mY7s0S) (image link)
[pip](https://ibb.co/cdCQLS) (image link)

When I run that exact same code in IDLE, I do return results.. I don't know what would be different?
[IDLE](https://ibb.co/nQfO77) (image link)

**Comment by mccartneyb** [comment]
Please disregard, I'm closing the issue. I refactored the project and called it something different, ran the same code, and returned reuslts in PyCharm now.. maybe it's my novice python exposure and I was overlooking something.. Thanks for getting back to me!
