### ISSUE TITLE
standings not update

### ISSUE THREAD

**Issue by MoonSungHoon** [panzarino/mlbgame#83]
`
import mlbgame
print(mlbgame.standings().divisions[0].teams[0].__dict__)
`
{'vs_left': '0-0', 'vs_central': '', 'home': '0-0', 'vs_right': '0-0', 'vs_division': '', 'vs_east': '', 'elim': '-', 'playoffs_flag_milb': '', 'extra_inn': '0-0', 'x_wl_seas': '-', 'playoffs_flag_mlb': '', 'gb': '-', 'interleague': '', 'division': 'National League East', 'is_wildcard_sw': 'Y', 'division_champ'
: 'Y', 'pct': '-', 'playoff_odds': 0.0, 'vs_west': '', 'last_ten': '0-0', 'clinched_sw': 'N', 'one_run': '0-0', 'points': '', 'place': 1, 'team_full': 'Philadelphia Phillies', 'team_abbrev': 'PHI', 'playoff_points_sw': 'N', 'wildcard_odds': 0.0, 'team_short': 'Philadelphia', 'l': 0, 'opp_runs': 0, 'sit_code': '
h0', 'w': 0, 'gb_wildcard': '-', 'away': '0-0', 'x_wl': '-', 'division_odds': 0.0, 'streak': '', 'wild_card': 'N', 'playoffs_sw': 'N', 'elim_wildcard': '-', 'file_code': 'phi', 'runs': 0, 'division_id': 204, 'team_id': 143}

**Comment by panzarino** [comment]
@MoonSungHoon I am not sure why the standings did not update. In any case, this seems like it is an issue with mlb.com, not the library. I will look into it.
