### ISSUE TITLE
Combine Games - Month vs. Year

### ISSUE THREAD

**Issue by mccartneyb** [panzarino/mlbgame#87]
how does the mlb.combine_games() work? i am able to run one month at a time, and get results almost instantaneously. I've even filtered it down game status != PRE_GAME, to exclude games that have not happened yet. However when i remove the month, and try to retrieve completed, 2018 games, it runs for over 15 minutes and I cant get anything to return. Any help would be much appreciated!

**one month:**
`import mlbgame

season = mlbgame.games(2018, 3, home='Indians', away='Indians')
games = mlbgame.combine_games(season)
for game in games:
    if game.game_status != 'PRE_GAME':
        print(game)`

**2018 completed:**
`import mlbgame

season = mlbgame.games(2018, home='Indians', away='Indians')
games = mlbgame.combine_games(season)
for game in games:
    if game.game_status != 'PRE_GAME':
        print(game)`

**Comment by panzarino** [comment]
@mccartneyb I don't think the issue is with combine games, I think the problem is that you are making too many requests to get data by getting an entire year.
