### ISSUE TITLE
Overview of Game Doesn't Show TV_Station

### ISSUE THREAD

**Issue by matt9790** [panzarino/mlbgame#93]
I am trying to write a code to show me the channel for today's Cubs game.  I tried this code to get the TV station for the game:

```
import mlbgame
from datetime import date
today = date.today()

gamestocheck = mlbgame.day(int(today.year),int(today.month),(int(today.day)))
for game in gamestocheck:
    if game.away_team == 'Cubs' or game.home_team == 'Cubs':
        print game
        ovvw = mlbgame.overview(game.game_id)
        print ovvw.tv_station

```

When I run this, I get:
**AttributeError: 'Overview' object has no attribute 'tv_station'**

The overview class, in game.py, shows that this should be a valid attribute.  Am I doing this incorrectly, or is this a no longer valid attribute?

Thanks for your time!

**Comment by ajbowler** [comment]
Relevant file: http://gd2.mlb.com/components/game/mlb/year_2018/month_04/day_27/gid_2018_04_27_milmlb_chnmlb_1/linescore.xml

I don't see it in linescore.xml for games in the past, at least for this season. It is possible that MLB dropped the field from their dataset perhaps.

**Comment by matt9790** [comment]
Well shoot.

Thanks for the quick response!

**Comment by trevor-viljoen** [comment]
@matt9790, add a feature request and I'll try to get to it when I have time. In the mean time, here's some code that will get the information you are looking for.

```python
import requests
from datetime import datetime
from dateutil import parser

datestring = '20180427'
base_url = 'http://mlb.mlb.com//lookup/json/named.mlb_broadcast_info.bam'
team_id = '112' #Cubs

if datestring:
    date = parser.parse(datestring).strftime('%Y-%m-%dT00:00:00')
    year = parser.parse(datestring).year
else:
    date = datetime.today().strftime('%Y-%m-%dT00:00:00')
    year = datetime.today().year

r = requests.get('{}?team_id={}&season={}'.format(base_url, team_id, year))
schedule = r.json()
schedule = schedule['mlb_broadcast_info']['queryResults']['row']
todays_games = [game for game in schedule if game['game_date'] == date]

if todays_games:
    for game in todays_games:
         home_away = 'home' if game['home_team_id'] == team_id else 'away'
         team_name = game['{}_team_full'.format(home_away)].split(' ')[-1]
         watch_listen = 'Watch' if game['source_type'] == 'TV' else 'Listen'
         print('{}: {} - {}'.format(watch_listen, team_name, game['source_desc'])

**Comment by matt9790** [comment]
I added this as a feature request (which means I opened an issue, I hope that is what you meant)

Thanks for the quick solution, it works perfectly!
