### ISSUE TITLE
base runners

### ISSUE THREAD

**Issue by lazuhrow93** [panzarino/mlbgame#95]
Hello, I am trying to get the current base runners of a game. I have game_id and the game is in progress but cant seem to find how to call that information. 

Thanks.

**Comment by lazuhrow93** [comment]
Actually I JUST found it. Its not on the overview object docuemtation I see here: [](http://panz.io/mlbgame/game.m.html). I saw on somebody's project using this API that they used "runner_on_1b". Whenever I tried it, it would say overview object does not have this value. But when I ran it when 1st base was occupied in game, the object did have this property. So I am guessing that this value only exists when its true? I am new to python so that's my assumption.


Thanks!

**Comment by panzarino** [comment]
@lazuhrow93 Yes, some attributes only exist during certain points in the game or for certain games, which seems to be the case here.
