### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by chisox721** [panzarino/mlbgame#96]
Hi there-I'm still in the process of learning Python so apologies if my problem is rudimentary but I downloaded mlbgame via pip (it does show up in my files with all contents) and that's about as far as I've gotten. To test it out I created a py file using the initial Mets home games example and after attempting to execute it in PowershellI I received this response: "AttributeError: module 'mlbgame' has no attribute 'games'".

I'm sure there is something random that I'm missing but as I mentioned I'm still learning Python. Any help would be greatly appreciated.

**Comment by panzarino** [comment]
I am not sure why this is happening, as it appears to be a local issue. If I had to guess, its because you have either a folder named `mlbgame` or a file named `mlbgame.py`.

**Comment by chisox721** [comment]
Yup, that was it. Thanks!
