### ISSUE TITLE
Is there a data dictionary anywhere for the stats in this package?

### ISSUE THREAD

**Issue by bbennett36** [panzarino/mlbgame#97]
I can't seem to find any real definitions for the fields used in the API. I was just wondering if there was a data dictionary in the API or any other site?

Thanks!

**Comment by panzarino** [comment]
The library used to include a statmap which gave definitions for each attribute, however that was removed. Most attributes are self explanatory by the name, so it didn't make sense to keep maintaining that file. Most of the attributes can be googled if you do not know what they stand for, and any attribute prefixed with `s_` just means season stats up until that game (series stats for playoff games).

**Comment by panzarino** [comment]
In addition, the documentation for each object contains a list of its attributes.
